services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_DB: your_db_name
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password

# volumes:
#   postgres_data: