services:
  prod:
    build: .
    command: sh -c "python manage.py migrate && gunicorn -w 4 --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/app
      - ./media:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
    depends_on:
      - prod
    restart: unless-stopped
    profiles:
      - prod
