services:
  prod:
    build: .
    command: sh -c "python manage.py migrate && gunicorn -w 4 --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/app
    env_file:
      - .env
    profiles:
      - prod
    restart: unless-stopped

  media-nginx:
    image: nginx:alpine
    volumes:
      - ./media:/usr/share/nginx/media:ro
      - ./nginx/media.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    profiles:
      - prod
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: |
        samambaiabar.com.br -> http://prod:8000
        samambaiabar.com.br/media -> http://media-nginx:80
      STAGE: production
    volumes:
      - https-portal-data:/var/lib/https-portal
    profiles:
      - prod
    restart: unless-stopped

volumes:
  https-portal-data:
